### ISSUE TITLE
Light will turn off but not on

### ISSUE THREAD

**Issue by mehuman** [stjohnjohnson/smartthings-mqtt-bridge#40]
Hi,
  I'm able to publish to turn a light off but not on or adjust the light level. I'll post my findings below. The light started on, set by the Smartthings app.

Commands:
mosquitto_pub -t 10.0.0.2 -p 1883 -t "smartthings/Living Room Light/switch" -m off
mosquitto_pub -t 10.0.0.2 -p 1883 -t "smartthings/Living Room Light/switch" -m on
mosquitto_pub -t 10.0.0.2 -p 1883 -t "smartthings/Living Room Light/level" -m 50

Live log from Smartthings:
c4615387-8aaf-4ebb-b4db-42336cf0f094  7:45:48 PM: debug Received device event from bridge: [name:Living Room Light, value:50, type:level]
c4615387-8aaf-4ebb-b4db-42336cf0f094  7:45:40 PM: debug Received device event from bridge: [name:Living Room Light, value:100, type:level]
c4615387-8aaf-4ebb-b4db-42336cf0f094  7:45:36 PM: debug Received device event from bridge: [status:OK]
c4615387-8aaf-4ebb-b4db-42336cf0f094  7:45:35 PM: debug Forwarding device event to bridge: {"path":"/push","body":{"name":"Living Room Light","value":"off","type":"switch"}}
c4615387-8aaf-4ebb-b4db-42336cf0f094  7:45:34 PM: debug Received device event from bridge: [name:Living Room Light, value:off, type:switch]

Log from mqtt bridge:
2016-05-14T23:48:27.101Z - info: Incoming message from MQTT: smartthings/Living Room Light/switch = off
2016-05-14T23:48:28.361Z - info: Incoming message from SmartThings: smartthings/Living Room Light/switch = off
2016-05-14T23:48:28.363Z - info: Incoming message from MQTT: smartthings/Living Room Light/switch = off
2016-05-14T23:48:28.363Z - info: Skipping duplicate message from: smartthings/Living Room Light/switch = off
2016-05-14T23:48:30.105Z - info: Incoming message from MQTT: smartthings/Living Room Light/switch = on
2016-05-14T23:48:30.105Z - info: Passing level instead of switch on
2016-05-14T23:48:32.616Z - info: Incoming message from MQTT: smartthings/Living Room Light/level = 50
2016-05-14T23:48:32.616Z - info: Skipping duplicate message from: smartthings/Living Room Light/level = 50

**Comment by ikonron** [comment]
I could only get mine to turn back on by changing the server.js file in /usr/local/lib/node_modules/smartthings-mqtt-bridge

I remmed out 260 -267 and I was able to turn it back on with HA:

This is why it wasn't turning on.
info: Incoming message from MQTT: smartthings/Basement Light 1/switch = off
info: Incoming message from MQTT: smartthings/Basement Light 1/switch = on
info: Passing level instead of switch on

Must have something to do with the brightness level st is reporting to the bridge making it think it is already on:.

Now on to figure out why the brightness level reporting or control isn't working.

**Comment by stjohnjohnson** [comment]
Interesting, because SmartThings should accept the brightness and turn the light on.
https://github.com/stjohnjohnson/smartthings-mqtt-bridge/blob/master/server.js#L260-L267

http://docs.smartthings.com/en/latest/capabilities-reference.html#switch-level
See comment:
```
    myswitch.setLevel(90) // also turns on the switch
```

**Comment by mehuman** [comment]
Taking a second look at this, I'm now getting this error in the live log. It happens when setting either the switch or trying to set the level.
Tried restarting the bridge and am getting the same error.

10:21:48 AM: error groovy.lang.MissingMethodException: No signature of method: java.lang.String.div() is applicable for argument types: (java.lang.Integer) values: [100]
Possible solutions: is(java.lang.Object), drop(int), wait(), trim(), find(), size() @ line 85

**Comment by stjohnjohnson** [comment]
What devicetype do you have for your light?  It sounds like theres a bug in that code.

**Comment by ikonron** [comment]
[image: Inline image 1]

Both of my lights are the same Osram. Experiencing the same results on
both. One thing I did notice was that when I tried dimming, the slider
moved in the app but the lamp did nothing. I haven't had time to mess with
it but hope to this weekend.

**Comment by scottosx** [comment]
I can verify that this condition is occurring as well. Commenting out lines 260 -267 restores the ability to turn the lights on and off. However, I still cannot set the level using the /level topic. 

I do get the status update from the console (if running without PM2)
info: Incoming message from MQTT: smartthings/Bedroom Light 1/level = 50

I do not see any change in the level slider in the app as indicated by Ikonron.

I have tested this on Osram Lightify as well as LIFX bulbs. 

Thanks for any insight and this awesome addition to the Smartthings arsenal.

**Comment by scottosx** [comment]
In the log I do see a similar error as reported above:

10:36:55 AM: debug Received device event from bridge: [name:Bedroom Light 1, value:50, type:level]
10:36:55 AM: error groovy.lang.MissingMethodException: No signature of method: java.lang.String.div() is applicable for argument types: (java.lang.Integer) values: [100]
Possible solutions: is(java.lang.Object), drop(int), wait(), trim(), dump(), size() @ line 527

**Comment by mehuman** [comment]
The lights I'm using are the Cree Connected Smartbulbs. 
http://creebulb.com/connected-60-watt-replacement-soft-white

**Comment by stjohnjohnson** [comment]
I'm thinking the problem is something in the Device Type for your light bulb.  We're sending an integer, while it looks like the device requires a string.  Very strange.  Not sure how to proceed here.

**Comment by kevinoconnor7** [comment]
I ran into this as well. It seems that the app is passing the bulb a string when it expects an int. I fixed it by updating the [levelAction](https://github.com/stjohnjohnson/smartthings-mqtt-bridge/blob/master/smartapps/stj/mqtt-bridge.src/mqtt-bridge.groovy#L643) to call `setLevel(value as int)`.

That resolved the issue for me, but I'm not sure it's going to be correct for all device types.

**Comment by mehuman** [comment]
^ This fix worked for me as well. I updated mine to read:

`def actionLevel(device, attribute, value) {
	device.setLevel(value)
    device.setLevel(value as int)
}`

Everything appears to be working, I still get an error about the value not being an int but the light turns on and I can adjust the level with the slider in HA.

Logs turning light on and adjusting the level:

0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:24 AM: debug [raw:0104 0008 0A 01 0140 00 4917 00 00 0000 0B 01 0400, profileId:0104, clusterId:0008, clusterInt:8, sourceEndpoint:0A, destinationEndpoint:01, options:0140, messageType:00, dni:4917, isClusterSpecific:false, isManufacturerSpecific:false, manufacturerId:0000, command:0B, direction:01, data:[04, 00]]
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:24 AM: debug DID NOT PARSE MESSAGE for description : catchall: 0104 0008 0A 01 0140 00 4917 00 00 0000 0B 01 0400
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:24 AM: debug level updated successfully
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:24 AM: debug description is catchall: 0104 0008 0A 01 0140 00 4917 00 00 0000 0B 01 0400
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:24 AM: debug description is read attr - raw: 49170A00080A00000020BC, dni: 4917, endpoint: 0A, cluster: 0008, size: 0A, attrId: 0000, result: success, encoding: 20, value: bc
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:23 AM: debug description is catchall: 0104 0006 0A 01 0140 00 4917 00 00 0000 0B 01 0100
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:23 AM: error groovy.lang.MissingMethodException: No signature of method: java.lang.String.div() is applicable for argument types: (java.lang.Integer) values: [100]
Possible solutions: drop(int), is(java.lang.Object), wait(), trim(), dump(), find()
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:10 AM: debug description is catchall: 0104 0006 0A 01 0140 00 4917 00 00 0000 0B 01 0100
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:08 AM: debug [raw:0104 0008 0A 01 0140 00 4917 00 00 0000 0B 01 0400, profileId:0104, clusterId:0008, clusterInt:8, sourceEndpoint:0A, destinationEndpoint:01, options:0140, messageType:00, dni:4917, isClusterSpecific:false, isManufacturerSpecific:false, manufacturerId:0000, command:0B, direction:01, data:[04, 00]]
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:08 AM: debug DID NOT PARSE MESSAGE for description : catchall: 0104 0008 0A 01 0140 00 4917 00 00 0000 0B 01 0400
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:08 AM: debug level updated successfully
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:08 AM: debug description is catchall: 0104 0008 0A 01 0140 00 4917 00 00 0000 0B 01 0400
0a40c8f8-5f19-4376-8607-ddc933bcc0b9  10:24:08 AM: error groovy.lang.MissingMethodException: No signature of method: java.lang.String.div() is applicable for argument types: (java.lang.Integer) values: [100]
Possible solutions: is(java.lang.Object), drop(int), wait(), trim(), dump(), size()

**Comment by kevinoconnor7** [comment]
Just make the code:

```groovy
def actionLevel(device, attribute, value) {
  device.setLevel(value as int)
}
```

That should work and you shouldn't get an errors

**Comment by mehuman** [comment]
You said earlier "That resolved the issue for me, but I'm not sure it's going to be correct for all device types." I was thinking that even though it errors it should make it universal for all device types to have both calls in. Thoughts?

**Comment by kevinoconnor7** [comment]
It's possible that an integer is always expected there, I just don't have enough devices to test with. If it works in your environment only passing in an int then I'd just leave it.

**Comment by stjohnjohnson** [comment]
Agreed, looks like my bad.  My devicetypes were fixing the string->int, but not Cree.  I have a PR open and @jer should be able to review it today.

Good find.

**Comment by stjohnjohnson** [comment]
+ smartthings-mqtt-bridge@1.3.4
